### PR TITLE
Fix #17

### LINKED ISSUE #17: Build error on Fedora 23
```
[ 54%] Built target wangle
[ 55%] Linking CXX executable bin/AcceptorTest
/usr/bin/ld: ../gmock/src/gmock-build/libgmock.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/AcceptorTest.dir/build.make:102: recipe for target 'bin/AcceptorTest' failed
make[2]: *** [bin/AcceptorTest] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/AcceptorTest.dir/all' failed
make[1]: *** [CMakeFiles/AcceptorTest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by guoxiao**
* Fix Build: ${CMAKE_THREAD_LIBS_INIT} not set
* Fix undefined reference to `__atomic_is_lock_free'

### CODE REVIEW

**Comment by viswanathgs** [comment]
Do you mind signing CLA so that I call pull your commit in? https://code.facebook.com/cla.

**Comment by guoxiao** [comment]
@viswanathgs I've already signed the CLA.

**Comment by viswanathgs** [comment]
Thanks, I merged this.

**Comment by guoxiao** [comment]
I find that on my new Fedora 23 (gcc 5.3.1) the commit https://github.com/facebook/wangle/commit/b1009e9670573d5cbb102303f149f8528f1881fb is not needed, which will break the build with a error `/usr/bin/ld: cannot find /usr/lib64/libatomic.so.1.1.0`.

Maybe some checks should be added to `CMakeList.txt` to deal with different compilers.

**Comment by viswanathgs** [comment]
We officially only support Ubuntu 14.04 for now, though it'll be awesome if you could get it fully working on Fedora 23!

**Pull request closed without merging**
