### PR TITLE
Fix bug of PipelineBase::removeHelper

### PR DESCRIPTION
**Pull request by EFLql**
There is a bug when removeHelper's arguments is handler == nullptr and checkEqual== false.Because std::vecotr<>::erase will return a iterator following the last removed element, In this case the loop should't add it when the function named removeAt has executed.

### CODE REVIEW

**Comment by snarkmaster** [comment]
@EFLql, we won't merge this commit as-is because it does not follow the ambient coding style. Please add whitespace around `{` and `}` as in the rest of the code.

Additionally, I would put `/* no increment */` into the third, now-empty expression of the `for` loop.

**Comment by fugalh** [comment]
Good catch. Yeah, this function is kind of a mess. I think this change probably makes it more correct, but I think it's still not very clear and I'm not very confident that there's no bugs.

Can you rewrite it using `std::remove_if` or similar?
http://en.cppreference.com/w/cpp/algorithm/remove
http://en.cppreference.com/w/cpp/algorithm

**Comment by EFLql** [comment]
@fugalh Yeah, it is clear by using std::remove_if.

**Comment by snarkmaster** [comment]
@EFLql, the unit test no longer passes with your change --

```
Start 11: PipelineTest
11/19 Test #11: PipelineTest .........................***Exception: Other  0.01 sec
      Start 12: CodecTest
```

**Pull request closed without merging**
