### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by donglei**
handlers

### CODE REVIEW

**Comment by donglei** [comment]
signed

**Comment by elliottneilclark** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1711645049095047/int_phab) to review.

**Comment by elliottneilclark** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1711645049095047/int_phab) to review.

**Comment by elliottneilclark** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1711645049095047/int_phab) to review.

**Comment by elliottneilclark** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1711645049095047/int_phab) to review.

**Comment by elliottneilclark** [comment]
Thanks for the patch.

**Pull request closed without merging**
