### PR TITLE
Add Echo Server/Client Example

### PR DESCRIPTION
**Pull request by jamperry**
I got a lot of feedback from my blog post saying there wasn't much examples to learn Wangle so I thought I'd write a few examples. I will start off with the most basic example - an Echo Server/Client.

### CODE REVIEW

**Comment by fugalh** [comment]
for posterity the blog post referred to: https://medium.com/swlh/starting-a-tech-startup-with-c-6b5d5856e6de#.e8nz2nn99

**Comment by viswanathgs** [comment]
Do you mind signing CLA so that I call pull your commit in? https://code.facebook.com/cla.

**Comment by fugalh** [comment]
Are you planning to write a blog post explaining the example in depth? If not, you or we could write some more in-depth explanation of the example code either in a text file here or in the comments.

**Comment by jamperry** [comment]
@viswanathgs No problem mate, signed
@fugalh Yes, I intend to write a blog post explaining Wangle's abstractions in more detail over this weekend. Once I've written it, I will merge its content into your README.md.

**Comment by fugalh** [comment]
Sweet!

**Comment by viswanathgs** [comment]
@jamperry, thanks for the PR. Looks awesome!

You missed adding the sources in https://github.com/facebook/wangle/blob/master/wangle/CMakeLists.txt. I added it though and committed your patch. It should be synced to github upstream within the hour.

**Pull request closed without merging**
